name: Deploy to WordPress.org

on:
  push:
    tags:
      - '*'

jobs:
  tag:
    name: New Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build WordPress Plugin (Pre-release)
        if: contains(github.ref, '-')
        id: build
        uses: 10up/action-wordpress-plugin-build-zip@stable
        env:
          SLUG: chatbudgie

      - name: WordPress Plugin Deploy (Release)
        if: "!contains(github.ref, '-')"
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: chatbudgie

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build.outputs.zip-path || steps.deploy.outputs.zip-path }}
          prerelease: ${{ contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
